### ISSUE TITLE
Slot edit view crashes on sep 11th in production 

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#807] opened 2023-09-09 07:46 UTC

**Comment by ikusteu** [comment] 2023-09-10 12:43
Did you mean attendance view?

Slot view is by week and the week including Sep 11th works fine for me.
Attendance however...crashes on Sep 11th

**Comment by ikusteu** [comment] 2023-09-10 18:13
After a fair amount of debugging, I've traced the bug to slot `y0wOTqPwCMROduP3DxOa`:
- in `slotsByDay` - the slot exists with it's entire data
- in `slots` - the slot doesn't exist
- in `attendance` - the slot exists, but doesn't have a date

Since the slot exists in `slotsByDay`, we see it in `/slots` view (since slots view uses `slotsByDay` to display slots grouped by month/day). If we were to "edit" the slot, the data would be pulled from the data displayed (from `slotsByDay`) and added to `slots` - thus creating a slot with the same id and the same data (as if it wasn't deleted). 

However, since slot entry in `attendance` holds only `attendances` (and empty object) and no `date`, it is not streamed back to the client, as subscription to `attendance` filters docs by date range (no date, the entry is not streamed back) and the crash (described in the ticket) happens when the selector is trying to group attendance data with slot data:
- the selector looks into `slotsByDay`, loops over all of the slots in a given day and looks for the corresponding attendance document
- when the attendance document, retrieved using `attendance[slotId]` (since attendance entries are id'd with the same id as their corresponding slot), it iterates over `.attendances` (collection of customer attendance data for the slot) to construct rows for each customer's attendance

Since attendance entry for `y0wOTqPwCMROduP3DxOa` doesn't contain a date, it's omitted from `attendance` data present in the client, but since it's included in `slotsByDay`, the client expects to (rightfully so) find the attendance entry for the corresponding slot and there it crashes (on "Cannot convert undefined or null into an object" - referring to the corresponding `attendances` property on a non-present `attendance[y0wOTqPwCMROduP3DxOa]`.

The solution....

1. Delete the slot
2. "Edit" the slot (in `/slots` view) and manually set the date of `y0wOTqPwCMROduP3DxOa` in `attendance` collection to `"2023-09-11"`

The root cause (asymmetry between `attendances`, `slots` and `slotsByDay`) seems a hard one to track/fix: We currently don't know whether this was fixed, was it a fluke, or is it still there and don't have a great way to test/handle it in the future). Additionally, this seems somewhat similar (or even related) to #804 . What we could do about it:
1. Tolerate these (known) errors:
  - add error handling to the code where these errors might happen (to proceed without crashing)
  - send reports to Sentry when these errors do happen - so that we know that the error is still present
  - add elaborate logging to the Firestore console (this seems like a drag)
2. Update the data model (or switch to Supabase) as discussed in #809

**Comment by silviot** [comment] 2023-09-11 07:00
@ikusteu Thanks for the analysis! I think we should work on making our code can survive these problems. My hunch is that the root cause for all this is the lack of transactional integrity.
Invariants are very important in a database. If an error occcurs in step 6 of 10 of serving a request, the first 6 steps should be rolled back, but we don't have such a thing here. I know, I mentioned it already, but it doesn't hurt to mention it again.

**Comment by ikusteu** [comment] 2023-09-15 16:30
@silviot I'm inclined to close this as it's been manually fixed in production and additional steps should be taken to track this/ensure it happens less and less often, but are not directly related to this ticket.

**Closed** 2023-09-16 14:42 UTC
Labels: bug
